### ISSUE TITLE
Best practice to share code between the server and the client (with external includes)

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/soundworks-template#10]
This is more a question than an issue, but current approach is quite unclear to me.

**What I want to do:** I want to share code, that is used in the server as well as in the client code, e.g. typescript classes or something like you did with the `schemas` in this project. Another example would be e.g. a shared `Utils` class. 

**The issue**: While this is working in a basic version, when I e.g. put the types/utils function on the server side, there seems to be an issue, when I use external libs, let's say the `lit-html` import as `import { html, Template } from "lit-html";` I get the following errors on the client side and at runtime:  

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: [...]\node_modules\lit-element\lit-element.js
require() of ES modules is not supported.
require() of [...]\node_modules\lit-element\lit-element.js from [...]\.build\server\types\uiModule.class.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename lit-element.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from [...]\node_modules\lit-element\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ([...]\.build\server\types\uiModule.class.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

**Note:** Maybe there is an easy fix to this. I just don't know where to start debugging/fixing this, since everything I searched for didn't provide any solution. There also seem to be some issues with some node versions in general: https://github.com/manuelbieh/authoring-modules-in-node I've upgrade the the latest stable release and the error still exists.

**Comment by b-ma** [comment]
Currently you have only one solution, which is not ideal but works:

Create a shared folder in clients, for example `src/clients/shared`, and put your classes (or whatever code) there. Then you can import the files from everywhere. The only weird thing is that from a server file your import will look like:

```js
import { MyClass } from '../clients/shared/MyClass.js'
```
or maybe just (because of the a build weirdness)
```js
import { MyClass } from '../shared/MyClass.js'
```

It is quite ugly I agree, but it should works. The right way would be to be able to create a kind of `src/shared` directory, but it won't compile for now because I have been too restrictive on the build strategy (cf. https://github.com/collective-soundworks/soundworks/issues/23).

**Warning**: Be aware, that if you want to share code between client and server, the code must be fully compatible on both side, i.e. you can't use browsers or node specific APIs. For example importing `lit-html` server-side will crash because node has no DOM API or whatever browser specific API.

About your specific issue, I don't really get what's the problem and what you want to achieve, because you say the error is client-side but looks like a node error stack. Maybe you could be more specific or point me to a repository so I can see what happens there.

About your note, yes writing libraries that work for both browsers and node is quite complicated at the moment, but things should get easier now that node support `import` natively since v14 or 16 I don't remember, but I didn't took the time to properly review that for now. The thing I ended up at this point is explained there : https://ircam-ismm.github.io/javascript/javascript-guidelines.html#import-and-export (but not all our libraries have been updated yet...). The other problem to properly work on such thing is that is to have clean and easy testing stack (that is itself maintainable...) which is really not easy to build.

**Comment by b-ma** [comment]
...so long thing short, there is currently no best practice :) but it should be fixed at some point

**Comment by schlenger** [comment]
Okay, that helps a lot right now, thank you for your effort. I guess I've missed some part of the server/client environment concept when trying to implement this.

What I wanted to do is to create some (typed) classes used in the application with have also some information within them how they should be rendered. There error here is - as you described - the issue that the code would need `lit-html` and also would be integrated on the server side.

I thought about this and as you said: a `shared/` folder next to `client` and `server` would be nice - in the build process the code then could be 'cleanly' compiled into the webpack on client side and transpiled on the server side. If you reach this point, it is probably a good idea to write some sentences about this in the docs.

Thank you so far :) I think we can close this issue, since the  'core problem' is already described in the other isses.
