### ISSUE TITLE
If switching the environment to "production", the application is not loaded

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/soundworks-template#5]
Since I can't find any information about changing the logging level within the production environment, I can't debug the whole process.

It seems like something is going wrong if the environment is switched (resources are generated and minified already). 

This is reproducible with the current checked in template project in a clean state.

I'm happy about any feedback regarding this issue.

**Comment by tschnz** [comment]
Any news on this?

**Comment by b-ma** [comment]
Looks like the minify script is broken because more and more dependencies publish es6 sources and the old-fashionned build system uses uglify-js which is itself pretty old-fashionned (cf. https://stackoverflow.com/a/47440295).

I managed to make it work using terser:
```
npm install terser
terser public/js/player.js > public/js/player.min.js
terser public/js/controller.js > public/js/controller.min.js
```

I actually won't fix this soon because this version will be deprecated in a very short time (and I'm in holidays right now), if you want to make a PR however it's welcome ! It's probably just a matter of modifying `module.exports.minify` in `/bin/transpiler` to use `terser` instead of `uglify-js`, and clean dependencies in the `package.json` accordingly

Bests,

**Comment by schlenger** [comment]
@b-ma Thanks for the explanation. If fixed this an stumbled upon another issue where the promise closure was not working correctly. The changes are combined in the PR. If the style isn't matching your expectations, you can modify the changes.

**Comment by b-ma** [comment]
that's merged, thanks !
